[app]
quit = "q"
search = "/"
daemon_menu = "d"
refresh = "r"
switch_tab_left = "t"
switch_tab_right = "T"
scroll_down = "j"
scroll_up = "k"

[services]
stop = "s"
start = "S"
toggle = " "

[logs]
toggle_auto_scroll = " "
